### ISSUE TITLE
"TODO: just leak for now, since deallocating always fails"

### ISSUE THREAD

**Issue by AEGQ** [pfent/rdma_tests#1]
The  deallocating  error is caused by the function **"~ReceiveQueue()"** which  is not be called after sharedReceiveQueue.release() . While **delete**  should be added to ensure that !

[Network.cpp#L94&L95:](https://github.com/pfent/rdma_tests/blob/master/rdma/Network.cpp#L94)

```
    ReceiveQueue* rq = sharedReceiveQueue.release();
    delete rq;
    CompletionQueuePair* cqp = sharedCompletionQueuePair.release();
    delete cqp;
```

**Reference:**
[http://en.cppreference.com/w/cpp/memory/unique_ptr/release](http://en.cppreference.com/w/cpp/memory/unique_ptr/release)

**PS:**

I have learned a lot about Verbs Api from this project , thanks and hope that will help **:)**

**Comment by pfent** [comment]
Thanks for the feedback, really apprechiated!
I debugged the code quite a while with @alexandervanrenen, but I didn't catch that.
